name: CI-CD

on:
  push:
    branches: [main, tv7]
  pull_request:
    branches: [main, tv7]

jobs:
  test-csrc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake

    - name: Prepare test script
      run: chmod +x run_ctests.sh

    - name: Run tests
      run: ./run_ctests.sh
	
  test-python:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.11, 3.12]  # Specify the desired Python versions

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install .[dev]

      - name: Run tests
        run: pytest --cov --cov-report=xml tests	
      
      # - name: Upload coverage reports to Codecov
        # uses: codecov/codecov-action@v4.0.1
        # with:
          # token:  ${{ secrets.CODECOV_TOKEN }}
          # slug: HarmonizedMRI/PulCeq


